# replicaCount -- replica count.
replicaCount: 1

# access_key_id -- Aliyun Access Key Id.
access_key_id: ""
# access_secret -- Aliyun Access Secret.
access_secret: ""
# region_id -- Aliyun Region Id.
region_id: "cn-shanghai"
# password -- Grafana admin password.
password: "admin"
# plugins -- Grafana plugin list.
plugins: "farski-blendstat-panel,grafana-simple-json-datasource,yesoreyeram-boomtheme-panel,https://github.com/sunny0826/aliyun-cms-grafana/archive/master.zip;aliyun-cms-grafana"
# anonymous -- grafana auth anonymous enables
anonymous: false
# dashboard -- module of dashboard
dashboard: 'dashboard,ecs,rds,mongodb,oss,eip,redis,slb'

image:
  # image.repository -- Image source repository name.
  repository: grafana/grafana
  # image.pullPolicy -- Image pull policy.
  pullPolicy: IfNotPresent

init_image:
  # init_image.repository -- Image source repository of init image.
  repository: guoxudongdocker/cms-grafana-jsonnet
  # init_image.tag -- Image tag of init image.
  tag: 0.1.0
  # init_image.pullPolicy -- Init image pull policy.
  pullPolicy: Always

backend_image:
  # backend_image.repository -- Image source repository of backend image.
  repository: guoxudongdocker/grafana-build
  # backend_image.tag -- Image tag of backend image.
  tag: 0.5.0
  # backend_image.pullPolicy -- Init image backend policy.
  pullPolicy: Always

cronjob_image:
  # cronjob_image.repository -- Image source repository of cronjob image.
  repository: guoxudongdocker/curl
  # cronjob_image.tag -- Image tag of cronjob image.
  tag: latest

# schedule -- CronJob schedule.
schedule: "30 2 * * *"

service:
  type: ClusterIP
  port: 80

ingress:
  # ingress.enabled -- Whether to open ingress.
  enabled: false
  annotations: {}
  # ingress.hosts -- Ingress hosts.
  hosts:
    - host: grafana.chart-example.local
      paths: ['/']

  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

backend_resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

affinity: {}
