# replicaCount -- replica count.
replicaCount: 1

# access_key_id -- Aliyun Access Key Id.
access_key_id: ""
# access_secret -- Aliyun Access Secret.
access_secret: ""
# region_id -- Aliyun Region Id.
region_id: "cn-shanghai"
# password -- Grafana admin password.
password: "admin"
# plugins -- Grafana plugin list.
plugins: "farski-blendstat-panel,grafana-simple-json-datasource,yesoreyeram-boomtheme-panel,https://github.com/sunny0826/aliyun-cms-grafana/archive/master.zip;aliyun-cms-grafana"
# grafana auth anonymous enables
anonymous: false

image:
  # image.repository -- Image source repository name.
  repository: grafana/grafana
  # image.pullPolicy -- Image pull policy.
  pullPolicy: IfNotPresent

backend_image:
  repository: guoxudongdocker/grafana-build
  tag: 0.5.0
  pullPolicy: Always

cronjob_image:
  repository: guoxudongdocker/curl
  tag: latest

# schedule -- CronJob schedule.
schedule: "30 2 * * *"

service:
  type: ClusterIP
  port: 80

ingress:
  # ingress.enabled -- Whether to open ingress.
  enabled: false
  annotations: {}
  # ingress.hosts -- Ingress hosts.
  hosts:
    - host: grafana.chart-example.local
      paths: ['/']

  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

backend_resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

affinity: {}
